import { Prisma, PrismaClient } from "@prisma/client";

type PlaceSeeder = Prisma.PlaceCreateManyInput & {
  categorySlugs: string[];
  islandSlug?: string;
};

export default async function run(prisma: PrismaClient) {
  const places: Array<PlaceSeeder> = [
    {
      countryId: "102",
      islandSlug: "jawa",
      stateId: "1829",
      cityId: "56816",
      categorySlugs: ["historicalsites"],
      title: "Tugu Yogyakarta",
      slug: "tugu-yogyakarta",
      description:
        "White-&-gold landmark on a traffic island, dating from 1889 & floodlit after dark.",
      imageUrl:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Yogyakarta_Indonesia_Tugu-Yogyakarta-01.jpg/800px-Yogyakarta_Indonesia_Tugu-Yogyakarta-01.jpg",
      latitude: -7.7829749,
      longitude: 110.3665674,
      zoom: 19,
      address:
        "Jl. Jend. Sudirman, Gowongan, Kec. Jetis, Kota Yogyakarta, Daerah Istimewa Yogyakarta 55233",
      isFeatured: true,
      position: 1,
    },
    {
      countryId: "102",
      islandSlug: "bali",
      stateId: "1826",
      cityId: "57013",
      categorySlugs: ["historicalsites"],
      title: "Tanah Lot",
      slug: "tanah-lot",
      description:
        "Traditional Balinese temple located on a small, rocky island & offering water vistas.",
      imageUrl:
        "https://cdn.pixabay.com/photo/2015/10/19/20/29/tanah-lot-996675_1280.jpg",
      latitude: -8.6212003,
      longitude: 115.0867082,
      zoom: 20,
      address: "Beraban, Kec. Kediri, Kabupaten Tabanan, Bali 82121",
      isFeatured: false,
      position: 7,
    },
    {
      countryId: "102",
      islandSlug: "jawa",
      stateId: "1825",
      cityId: "56731",
      categorySlugs: ["localgovernmentoffice", "historicalsites"],
      title: "Gedung Sate",
      slug: "gedung-sate",
      description:
        "Grand Dutch colonial administration building dating to the 1920s, now West Java's government house.",
      imageUrl:
        "https://asset.kompas.com/crops/D-48F5-nznZLRdljeLyENC5eBHw=/126x217:926x750/750x500/data/photo/2023/08/13/64d87d100ad37.jpg",
      latitude: -6.9024662,
      longitude: 107.6161269,
      zoom: 14,
      address:
        "Jl. Diponegoro No.22, Citarum, Kec. Bandung Wetan, Kota Bandung, Jawa Barat 40115",
      isFeatured: true,
      position: 3,
    },
    {
      countryId: "102",
      stateId: "1825",
      cityId: "56731",
      categorySlugs: ["mosque", "historicalsites"],
      title: "Masjid Raya Al Jabbar",
      slug: "masjid-raya-al-jabbar",
      description: "Mosque",
      imageUrl:
        "https://upload.wikimedia.org/wikipedia/commons/8/8c/Al_Jabbar_Mosque.jpg",
      latitude: -6.9477666,
      longitude: 107.6945773,
      zoom: 14,
      address:
        "Jl. Cimincrang No.14, Cimenerang, Kec. Gedebage, Kota Bandung, Jawa Barat 40292",
      isFeatured: true,
      position: 6,
    },
    {
      countryId: "102",
      islandSlug: "bali",
      stateId: "1805",
      cityId: "56723",
      categorySlugs: ["historicalsites"],
      title: "Bundaran HI",
      slug: "bundaran-hi",
      description:
        "The Selamat Datang Monument is located in the center of a roundabout known as Bundaran Hotel Indonesia or Bundaran HI (Indonesian for Hotel Indonesia Roundabout)",
      imageUrl:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Jakarta_Bundaran_HI_.jpg/1200px-Jakarta_Bundaran_HI_.jpg",
      latitude: -6.1952368,
      longitude: 106.8230805,
      zoom: 18,
      address:
        "Menteng, Kec. Menteng, Kota Jakarta Pusat, Daerah Khusus Ibukota Jakarta",
      isFeatured: true,
      position: 4,
    },
    {
      countryId: "102",
      islandSlug: "bali",
      stateId: "1827",
      cityId: "56803",
      categorySlugs: ["historicalsites"],
      title: "Monument Surabaya",
      slug: "monument-surabaya",
      description:
        "Landmark statue symbolic of Surabaya city, featuring a shark & crocodile tussling amid seaweed.",
      imageUrl:
        "https://cdn0-production-images-kly.akamaized.net/Kk8K3Hudrxp1fVOn-1FpQlmPA-U=/800x800/smart/filters:quality(75):strip_icc():format(webp)/kly-media-production/medias/763542/original/019580500_1415592126-1_travelmatekamu.jpg",
      latitude: -7.2960492,
      longitude: 112.7387012,
      zoom: 18,
      address:
        "Jl. Diponegoro No.1-B, Darmo, Kec. Wonokromo, Surabaya, Jawa Timur 60241",
      isFeatured: true,
      position: 5,
    },
    {
      countryId: "102",
      stateId: "1802",
      cityId: "56505",
      categorySlugs: ["historicalsites"],
      title: "Borobudur Temple",
      slug: "borobudur-temple",
      description: "9th-century Mahayana Buddhist temple.",
      imageUrl:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Stupa_Borobudur.jpg/300px-Stupa_Borobudur.jpg",
      latitude: -7.6078745,
      longitude: 110.2037512,
      zoom: 14,
      address:
        "Kawasan Candi Borobudur, Borobudur, Magelang, Jawa Tengah 56553",
      isFeatured: true,
      position: 2,
    },
    {
      countryId: "102",
      stateId: "1829",
      cityId: "56338",
      categorySlugs: ["beach"],
      title: "Parangtritis Beach",
      slug: "parangtritis-beach",
      description: "Famous for its sunsets and mystic legends.",
      imageUrl:
        "https://static.gatra.com/foldershared/images/2019/fuad/05-May/para.jpg",
      latitude: -8.0262033,
      longitude: 110.3158671,
      zoom: 14,
      address: "Jl. Parangtritis Km. 28, Bantul, Yogyakarta 55772",
      isFeatured: false,
      position: 8,
    },
    {
      countryId: "102",
      islandSlug: "jawa",
      stateId: "1829",
      cityId: "56637",
      categorySlugs: ["temple"],
      title: "Prambanan Temple",
      slug: "prambanan-temple",
      description: "9th-century Hindu temple compound.",
      imageUrl:
        "https://unsplash.com/photos/an-aerial-view-of-a-temple-in-the-middle-of-a-field-TCIhwzzsQKA",
      latitude: -7.7519567,
      longitude: 110.4919415,
      zoom: 14,
      address:
        "Jl. Raya Solo - Yogyakarta No.16, Kranggan, Bokoharjo, Kec. Prambanan, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55572",
      isFeatured: false,
      position: 9,
    },
    {
      countryId: "102",
      stateId: "1818",
      cityId: "56721",
      categorySlugs: ["nationalpark"],
      title: "Komodo National Park",
      slug: "komodo-national-park",
      description: "Home to the Komodo dragon.",
      imageUrl:
        "https://upload.wikimedia.org/wikipedia/commons/3/3a/Komodo_dragon_at_Komodo_National_Park.jpg",
      latitude: -8.5654485,
      longitude: 119.4880321,
      zoom: 14,
      address: "Komodo, Nusa Tenggara Timur",
    },
    {
      countryId: "102",
      stateId: "1826",
      cityId: "56322",
      categorySlugs: ["beach"],
      title: "Kuta Beach",
      slug: "kuta-beach",
      description: "Popular tourist destination in Bali.",
      imageUrl:
        "https://www.gotravelaindonesia.com/wp-content/uploads/Pantai-Kuta-Bali-beach.jpg",
      latitude: -8.7180219,
      longitude: 115.1628847,
      zoom: 14,
      address: "Kec. Kuta, Kabupaten Badung, Bali",
    },
    {
      countryId: "102",
      stateId: "1826",
      cityId: "56827",
      categorySlugs: ["temple"],
      title: "Uluwatu Temple",
      slug: "uluwatu-temple",
      description: "Balinese sea temple.",
      imageUrl:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Pura_Luhur_Uluwatu_2017-08-17_%2834%29.jpg/640px-Pura_Luhur_Uluwatu_2017-08-17_%2834%29.jpg",
      latitude: -8.8290434,
      longitude: 115.0821739,
      zoom: 14,
      address: "Pecatu, Kuta Selatan, Kabupaten Badung, Bali",
    },
    {
      countryId: "102",
      stateId: "1805",
      cityId: "56723",
      categorySlugs: ["historicalsites", "museum"],
      title: "National Monument (Monas)",
      slug: "monas",
      description: "Iconic monument symbolizing Indonesia's independence.",
      imageUrl:
        "https://upload.wikimedia.org/wikipedia/id/b/b1/Merdeka_Square_Monas_02.jpg",
      latitude: -6.175392,
      longitude: 106.827153,
      zoom: 14,
      address:
        "Merdeka Square, Jalan Lapangan Monas, Gambir, Kecamatan Gambir, Kota Jakarta Pusat, Daerah Khusus Ibukota Jakarta 10110",
    },
    {
      countryId: "102",
      stateId: "1805",
      cityId: "56726",
      categorySlugs: ["museum"],
      title: "Jakarta History Museum (Fatahillah Museum)",
      slug: "jakarta-history-museum",
      description: "Museum showcasing Jakarta's history.",
      imageUrl:
        "https://museum.kemdikbud.go.id/storage/assets/images/museums/191/2019-11-27_907.jpg",
      latitude: -6.1351947,
      longitude: 106.8107251,
      zoom: 14,
      address:
        "Taman Fatahillah No.1, Pinangsia, Kec. Taman Sari, Kota Jakarta Barat, Daerah Khusus Ibukota Jakarta 11110",
    },
    {
      countryId: "102",
      stateId: "1805",
      cityId: "56723",
      categorySlugs: ["shopping"],
      title: "Grand Indonesia Mall",
      slug: "grand-indonesia-mall",
      description: "Large upscale shopping mall.",
      imageUrl:
        "https://www.grand-indonesia.com/wp-content/uploads/2021/02/web-gi-banner.jpg",
      latitude: -6.1950412,
      longitude: 106.8207104,
      zoom: 14,
      address:
        "Jl. MH Thamrin No.1, Menteng, Kec. Menteng, Kota Jakarta Pusat, Daerah Khusus Ibukota Jakarta 10310",
    },
    {
      countryId: "102",
      stateId: "1827",
      cityId: "56600",
      categorySlugs: ["volcano"],
      title: "Mount Bromo",
      slug: "mount-bromo",
      description: "Active volcano and popular tourist destination.",
      imageUrl:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Bromo-Semeru-Batok-Widodaren.jpg/800px-Bromo-Semeru-Batok-Widodaren.jpg",
      latitude: -7.9424721,
      longitude: 112.9427125,
      zoom: 14,
      address: "Area Gn. Bromo, Podokoyo, Kec. Tosari, Pasuruan, Jawa Timur",
    },
    {
      countryId: "102",
      stateId: "1818",
      cityId: "56721",
      categorySlugs: ["beach"],
      title: "Pink Beach",
      slug: "pink-beach",
      description: "Beach with pink sand.",
      imageUrl:
        "https://asset.kompas.com/crops/O1-Fz_6DqwjFwgak8_CWWiebFeQ=/0x83:1000x750/750x500/data/photo/2020/02/24/5e538e7bda8fd.jpg",
      latitude: -8.6013722,
      longitude: 119.5171736,
      zoom: 14,
      address: "Komodo Island, East Nusa Tenggara",
    },
    {
      countryId: "102",
      stateId: "1827",
      cityId: "56500",
      categorySlugs: ["waterfall"],
      title: "Tumpak Sewu Waterfall",
      slug: "tumpak-sewu-waterfall",
      description: "Scenic waterfall with a large drop.",
      imageUrl:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Air_Terjun_Tumpak_Sewu.jpg/1200px-Air_Terjun_Tumpak_Sewu.jpg",
      latitude: -8.2302073,
      longitude: 112.9149689,
      zoom: 14,
      address:
        "Jalan Tumpak Sewu, Besukcukit, Sidomulyo, Kec. Pronojiwo, Kabupaten Lumajang, Jawa Timur 67374",
    },
    {
      countryId: "102",
      stateId: "1827",
      cityId: "56600",
      categorySlugs: ["nationalpark"],
      title: "Bromo Tengger Semeru National Park",
      slug: "bromo-tengger-semeru-national-park",
      description: "National park known for its volcanoes.",
      imageUrl:
        "https://upload.wikimedia.org/wikipedia/commons/a/a4/Andhika_bayu_nugraha-taman_nasional_bromo_tengger_semeru.jpg",
      latitude: -8.0014,
      longitude: 112.9526,
      zoom: 14,
      address:
        "Jalan Tumpak Sewu, Besukcukit, Sidomulyo, Kec. Pronojiwo, Kabupaten Lumajang, Jawa Timur 67374",
    },
    {
      countryId: "102",
      stateId: "1814",
      cityId: "56499",
      categorySlugs: ["island"],
      title: "Gili Islands",
      slug: "gili-islands",
      description: "Group of three small islands known for their beaches.",
      imageUrl:
        "https://upload.wikimedia.org/wikipedia/commons/d/df/Gili_Islands_%26_Gunung_Rinjiani%2C_Lombok%2C_Indonesia.jpg",
      latitude: -8.3518011,
      longitude: 116.0355636,
      zoom: 14,
      address:
        "Gili Indah, Kec. Pemenang, Kabupaten Lombok Utara, Nusa Tenggara Barat",
    },
    {
      countryId: "102",
      stateId: "1826",
      cityId: "56460",
      categorySlugs: ["island"],
      title: "Nusa Penida",
      slug: "nusa-penida",
      description: "Island known for its scenic views and clear waters.",
      imageUrl:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Kelingking_Beach_%282022%29.jpg/1200px-Kelingking_Beach_%282022%29.jpg",
      latitude: -8.7411569,
      longitude: 115.446332,
      zoom: 14,
      address: "Kec. Nusa Penida, Kabupaten Klungkung, Bali",
    },
    {
      countryId: "102",
      stateId: "1826",
      cityId: "56379",
      categorySlugs: ["waterfall"],
      title: "Sekumpul Waterfall",
      slug: "sekumpul-waterfall",
      description: "Waterfall in a lush green area.",
      imageUrl:
        "https://travelsetu.com/apps/uploads/new_destinations_photos/destination/2024/06/27/17a4051a7d35826a821e60e9404ab937_1000x1000.jpeg",
      latitude: -8.1906335,
      longitude: 115.1584101,
      zoom: 14,
      address: "Bebetin, Kec. Sawan, Kabupaten Buleleng, Bali",
    },
    {
      countryId: "102",
      stateId: "1792",
      cityId: "56867",
      categorySlugs: ["lake"],
      title: "Lake Toba",
      slug: "lake-toba",
      description: "Large natural lake in a volcanic crater.",
      imageUrl:
        "https://upload.wikimedia.org/wikipedia/commons/a/ae/Indonesia_-_Lake_Toba_%2826224127503%29.jpg",
      latitude: 2.6110932,
      longitude: 98.6711577,
      zoom: 14,
      address: "North Sumatra",
    },
    {
      countryId: "102",
      stateId: "1814",
      cityId: "56497",
      categorySlugs: ["beach"],
      title: "Tanjung Aan Beach",
      slug: "tanjung-aan-beach",
      description: "White sandy beach with clear blue waters.",
      imageUrl:
        "https://upload.wikimedia.org/wikipedia/commons/e/e4/BIRUNYA_TANJUNG_AAN.jpg",
      latitude: -8.9101022,
      longitude: 116.3198844,
      zoom: 14,
      address: "Lombok, West Nusa Tenggara",
    },
    {
      countryId: "102",
      stateId: "1795",
      cityId: "56662",
      categorySlugs: ["cultural"],
      title: "Toraja Traditional Houses",
      slug: "toraja-traditional-houses",
      description: "Traditional houses with unique architecture.",
      imageUrl:
        "https://upload.wikimedia.org/wikipedia/commons/b/b2/Traditional_Toraja_House.JPG",
      latitude: -2.9667,
      longitude: 119.8995,
      zoom: 14,
      address: "South Sulawesi",
    },
    {
      countryId: "102",
      stateId: "1826",
      cityId: "57046",
      categorySlugs: ["historicalsites"],
      title: "Ubud Palace",
      slug: "ubud-palace",
      description: "Historical royal palace in Ubud.",
      imageUrl:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Ubud_Palace_%282022%29.jpg/1200px-Ubud_Palace_%282022%29.jpg",
      latitude: -8.5065924,
      longitude: 115.2600135,
      zoom: 14,
      address:
        "Jl. Raya Ubud No.8, Ubud, Kecamatan Ubud, Kabupaten Gianyar, Bali 80571",
      isFeatured: false,
      position: null,
    },
    {
      countryId: "102",
      stateId: "1825",
      cityId: "56196",
      categorySlugs: ["shopping"],
      title: "Trans Studio Mall Bandung",
      slug: "trans-studio-mall-bandung",
      description: "Large shopping mall in Bandung.",
      imageUrl:
        "https://upload.wikimedia.org/wikipedia/commons/a/a6/Bandung%2C_Bandung_City%2C_West_Java%2C_Indonesia_-_panoramio_%283%29.jpg",
      latitude: -6.9255367,
      longitude: 107.6340927,
      zoom: 14,
      address:
        "Jl. Gatot Subroto No.289, Cibangkong, Kec. Batununggal, Kota Bandung, Jawa Barat 40273",
      isFeatured: false,
      position: null,
    },
    {
      countryId: "102",
      stateId: "1826",
      cityId: "56263",
      categorySlugs: ["beach"],
      title: "Sanur Beach",
      slug: "sanur-beach",
      description: "Popular beach in Bali.",
      imageUrl:
        "https://www.balimagictour.com/wp-content/uploads/sanur-beach.jpg",
      latitude: -8.7042307,
      longitude: 115.254543,
      zoom: 14,
      address: "Sanur, Denpasar, Bali",
      isFeatured: false,
      position: null,
    },
    {
      countryId: "102",
      stateId: "1826",
      cityId: "56890",
      categorySlugs: ["beach"],
      title: "Nusa Dua Beach",
      slug: "nusa-dua-beach",
      description: "High-end beach resort area.",
      imageUrl:
        "https://asset.kompas.com/crops/MpgWLXIZOyrcx1wZQ3kXrfdV-EI=/2x0:848x564/750x500/data/photo/2022/01/25/61f000083afed.jpg",
      latitude: -8.7985273,
      longitude: 115.2100453,
      zoom: 14,
      address: "Benoa, Kec. Kuta Sel., Kabupaten Badung, Bali",
      isFeatured: false,
      position: null,
    },
    {
      countryId: "102",
      stateId: "1818",
      cityId: "56721",
      categorySlugs: ["island"],
      title: "Padar Island",
      slug: "padar-island",
      description: "Scenic island with panoramic views.",
      imageUrl:
        "https://upload.wikimedia.org/wikipedia/commons/a/a5/Pulau_Padar_1.jpg",
      latitude: -8.6626241,
      longitude: 119.5491269,
      zoom: 14,
      address:
        "Komodo, Kec. Komodo, Kabupaten Manggarai Barat, Nusa Tenggara Timur",
      isFeatured: false,
      position: null,
    },
    {
      countryId: "102",
      stateId: "1802",
      cityId: "57061",
      categorySlugs: ["volcano"],
      title: "Mount Merapi",
      slug: "mount-merapi",
      description: "Active stratovolcano in Yogyakarta.",
      imageUrl:
        "https://img.jakpost.net/c/2021/02/19/2021_02_19_110706_1613721093._large.jpg",
      latitude: -7.540696,
      longitude: 110.4354244,
      zoom: 14,
      address:
        "Dusun 2, Suroteleng, Kec. Selo, Kabupaten Boyolali, Jawa Tengah",
      isFeatured: false,
      position: null,
    },
    {
      countryId: "102",
      stateId: "1826",
      cityId: "56981",
      categorySlugs: ["waterfall"],
      title: "Gitgit Waterfall",
      slug: "gitgit-waterfall",
      description: "Famous waterfall in Bali.",
      imageUrl:
        "https://upload.wikimedia.org/wikipedia/commons/e/e2/Gitgit_Waterfall%2C_Campuhan_area%2C_Bali%2C_Indonesia.jpg",
      latitude: -8.1960943,
      longitude: 115.1323784,
      zoom: 14,
      address:
        "Jl. Raya Bedugul - Singaraja, Gitgit, Kec. Sukasada, Kabupaten Buleleng, Bali 81161",
      isFeatured: false,
      position: null,
    },
    {
      countryId: "102",
      stateId: "1829",
      cityId: "56816",
      categorySlugs: ["cultural"],
      title: "Kraton Yogyakarta",
      slug: "kraton-yogyakarta",
      description: "The palace of the Yogyakarta Sultanate.",
      imageUrl:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Kraton_Yogyakarta_Pagelaran.jpg/1200px-Kraton_Yogyakarta_Pagelaran.jpg",
      latitude: -7.8052792,
      longitude: 110.3616282,
      zoom: 14,
      address:
        "Jalan Rotowijayan Blok No.1, Panembahan, Kota Yogyakarta, Daerah Istimewa Yogyakarta 55131",
      isFeatured: false,
      position: null,
    },
    {
      countryId: "102",
      stateId: "1827",
      cityId: "56600",
      categorySlugs: ["volcano"],
      title: "Mount Ijen",
      slug: "mount-ijen",
      description: "Active volcano known for its blue flames.",
      imageUrl:
        "https://www.indonesia.travel/content/dam/indtravelrevamp/en/destinations/java/east-java/ijen-crater/ijen-crater.jpg",
      latitude: -8.0587806,
      longitude: 114.2321135,
      zoom: 14,
      address: "East Java",
      isFeatured: false,
      position: null,
    },
    {
      countryId: "102",
      stateId: "1829",
      cityId: "56414",
      categorySlugs: ["beach"],
      title: "Indrayanti Beach",
      slug: "indrayanti-beach",
      description: "Popular beach with white sand and clear waters.",
      imageUrl:
        "https://visitingjogja.jogjaprov.go.id/en/wp-content/uploads/2019/03/820.jpg",
      latitude: -8.1507833,
      longitude: 110.6099911,
      zoom: 14,
      address: "Tepus, Gunung Kidul, Yogyakarta",
      isFeatured: false,
      position: null,
    },
    {
      countryId: "102",
      stateId: "1826",
      cityId: "56827",
      categorySlugs: ["beach"],
      title: "Dreamland Beach",
      slug: "dreamland-beach",
      description: "Beautiful beach with white sand and surf.",
      imageUrl:
        "https://baliuntold.com/wp-content/uploads/2024/02/Dreamland-Beach-in-Uluwatu-Bali.jpg",
      latitude: -8.799544,
      longitude: 115.1113493,
      zoom: 14,
      address: "Pecatu, Bali",
      isFeatured: false,
      position: null,
    },
    {
      countryId: "102",
      stateId: "1826",
      cityId: "56302",
      categorySlugs: ["beach"],
      title: "Balangan Beach",
      slug: "balangan-beach",
      description: "Scenic beach with good surf.",
      imageUrl:
        "https://www.water-sport-bali.com/wp-content/uploads/2013/02/Pantai-Balangan-Bali-Feature-Image.jpg",
      latitude: -8.7922633,
      longitude: 115.1221238,
      zoom: 14,
      address: "Kec. Kuta Sel., Kabupaten Badung, Bali",
      isFeatured: false,
      position: null,
    },
    {
      countryId: "102",
      stateId: "1802",
      cityId: "56459",
      categorySlugs: ["historicalsites"],
      title: "Sewu Temple",
      slug: "sewu-temple",
      description: "Buddhist temple complex near Prambanan.",
      imageUrl:
        "https://upload.wikimedia.org/wikipedia/commons/2/26/Candi_Sewu_viewed_from_the_south%2C_23_November_2013.jpg",
      latitude: -7.7439132,
      longitude: 110.4903588,
      zoom: 14,
      address:
        "Jl. Raya Solo - Yogyakarta No.KM.16, Bugisan, Kec. Prambanan, Kabupaten Sleman, Daerah Istimewa Yogyakarta",
      isFeatured: false,
      position: null,
    },
    {
      countryId: "102",
      stateId: "1825",
      cityId: "56196",
      categorySlugs: ["park"],
      title: "Taman Hutan Raya Ir. H. Djuanda",
      slug: "taman-hutan-raya-ir-h-djuanda",
      description: "Urban forest park in Bandung.",
      imageUrl:
        "https://assets-a1.kompasiana.com/items/album/2021/12/22/ayobdg-tahura-djuanda-ditutup-kavin-faza2-61c21edc06310e58953b63b3.jpg",
      latitude: -6.8589267,
      longitude: -6.8589267,
      zoom: 14,
      address:
        "Kompleks Tahura, Jl. Ir. H. Juanda No.99, Ciburial, Kec. Cimenyan, Kabupaten Bandung, Jawa Barat 40198",
      isFeatured: false,
      position: null,
    },
    {
      countryId: "102",
      stateId: "1805",
      cityId: "56722",
      categorySlugs: ["museum"],
      title: "Museum Macan",
      slug: "museum-macan",
      description: "Modern art museum in Jakarta.",
      imageUrl:
        "https://casaindonesia.com/lkgallery/teaser/image_time-out_s_44_20180922182733hu9wdv.jpg",
      latitude: -6.1910381,
      longitude: 106.7654109,
      zoom: 14,
      address:
        "AKR Tower Level M, Jl. Panjang No.5, Kb. Jeruk, Kec. Kb. Jeruk, Kota Jakarta Barat, Daerah Khusus Ibukota Jakarta 11530",
      isFeatured: false,
      position: null,
    },
    {
      countryId: "102",
      stateId: "1827",
      cityId: "56500",
      categorySlugs: ["volcano"],
      title: "Mount Semeru",
      slug: "mount-semeru",
      description: "Highest volcano in Java.",
      imageUrl:
        "https://upload.wikimedia.org/wikipedia/commons/1/12/Semeru.jpg",
      latitude: -8.1076957,
      longitude: 112.9121078,
      zoom: 14,
      address:
        "Ngampo, Pasrujambe, Kec. Pasrujambe, Kabupaten Lumajang, Jawa Timur",
      isFeatured: false,
      position: null,
    },
    {
      countryId: "102",
      stateId: "1826",
      cityId: "56302",
      categorySlugs: ["beach"],
      title: "Jimbaran Beach",
      slug: "jimbaran-beach",
      description: "Popular beach known for seafood restaurants.",
      imageUrl:
        "https://mediaim.expedia.com/destination/1/33667914376a9055df144892291b2b81.jpg",
      latitude: -8.7750576,
      longitude: 115.1598931,
      zoom: 14,
      address: "Jimbaran, Kec. Kuta Sel., Kabupaten Badung, Bali",
      isFeatured: false,
      position: null,
    },
    {
      countryId: "102",
      stateId: "1826",
      cityId: "56322",
      categorySlugs: ["beach"],
      title: "Padang Padang Beach",
      slug: "padang-padang-beach",
      description: "Scenic beach with surf spots.",
      imageUrl:
        "https://ik.imagekit.io/tvlk/blog/2020/01/shutterstock_435665278.jpg",
      latitude: -8.8111471,
      longitude: 115.1012494,
      zoom: 14,
      address: "Pecatu, Kec. Kuta Sel., Kabupaten Badung, Bali",
      isFeatured: false,
      position: null,
    },
    {
      countryId: "102",
      stateId: "1827",
      cityId: "56600",
      categorySlugs: ["waterfall"],
      title: "Madakaripura Waterfall",
      slug: "madakaripura-waterfall",
      description: "Scenic waterfall in East Java.",
      imageUrl:
        "https://www.journeyera.com/wp-content/uploads/2018/11/madakaripura-waterfall-east-java-8840.jpg",
      latitude: -7.847866,
      longitude: 113.0135465,
      zoom: 14,
      address:
        "5228+VC5, Branggah, Sapih, Kec. Lumbang, Kabupaten Probolinggo, Jawa Timur 67183",
      isFeatured: false,
      position: null,
    },
    {
      countryId: "102",
      stateId: "1826",
      cityId: "56379",
      categorySlugs: ["beach"],
      title: "Lovina Beach",
      slug: "lovina-beach",
      description: "Beach famous for dolphin sightings.",
      imageUrl:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Morning_of_Lovina_Beach_200507-6.jpg/1200px-Morning_of_Lovina_Beach_200507-6.jpg",
      latitude: -8.1605875,
      longitude: 115.0196154,
      zoom: 14,
      address: "Kec. Buleleng, Kabupaten Buleleng, Bali",
      isFeatured: false,
      position: null,
    },
    {
      countryId: "102",
      stateId: "1826",
      cityId: "56884",
      categorySlugs: ["beach"],
      title: "Menjangan Island",
      slug: "menjangan-island",
      description: "Island known for snorkeling and diving.",
      imageUrl:
        "https://lovebali.baliprov.go.id/storage/touriest_destinations/img-165838324862d8eb90cf2f0.jpg",
      latitude: -8.0983118,
      longitude: 114.5047003,
      zoom: 14,
      address: "Sumber Klampok, Kec. Gerokgak, Kabupaten Buleleng, Bali",
      isFeatured: false,
      position: null,
    },
    {
      countryId: "102",
      stateId: "1829",
      cityId: "56637",
      categorySlugs: ["historicalsites"],
      title: "Ratu Boko Palace",
      slug: "ratu-boko-palace",
      description: "Archaeological site and palace complex.",
      imageUrl:
        "https://upload.wikimedia.org/wikipedia/commons/7/77/Kraton_Ratu_Boko_%28Ratu_Boko_Temple%29_in_Yogyakarta%2C_Indonesia_03.jpg",
      latitude: -7.7705363,
      longitude: 110.4868409,
      zoom: 14,
      address:
        "Jl. Raya Piyungan - Prambanan No.2, Gatak, Bokoharjo, Kec. Prambanan, Kabupaten Sleman, Daerah Istimewa Yogyakarta 5572",
      isFeatured: false,
      position: null,
    },
    {
      countryId: "102",
      stateId: "1827",
      cityId: "56301",
      categorySlugs: ["beach"],
      title: "Papuma Beach",
      slug: "papuma-beach",
      description: "Beautiful beach with white sand and clear waters.",
      imageUrl:
        "https://awsimages.detik.net.id/api/wm/2019/01/10/b4faae86-9fe7-4ee2-a2e1-105c8e5fc8ae_169.jpeg?wid=60&w=650&v=1&t=jpeg",
      latitude: -8.4310001,
      longitude: 113.5533954,
      zoom: 14,
      address: "Jember, East Java",
      isFeatured: false,
      position: null,
    },
    {
      countryId: "102",
      stateId: "1826",
      cityId: "56884",
      categorySlugs: ["beach"],
      title: "Crystal Bay",
      slug: "crystal-bay",
      description: "Beautiful beach on Nusa Penida.",
      imageUrl:
        "https://awsimages.detik.net.id/community/media/visual/2022/10/28/crystal-bay-nusa-penida-2.jpeg?w=1024",
      latitude: -8.7151611,
      longitude: 37.4121815,
      zoom: 14,
      address: "Nusa Penida, Bali",
      isFeatured: false,
      position: null,
    },
    {
      countryId: "102",
      stateId: "1826",
      cityId: "56884",
      categorySlugs: ["beach"],
      title: "Atuh Beach",
      slug: "atuh-beach",
      description: "Scenic beach on Nusa Penida.",
      imageUrl:
        "https://ucarecdn.com/3a6f53c5-6ef1-4a72-9b8d-d5eb2b9fe9d7/-/scale_crop/400x300/",
      latitude: -8.7733901,
      longitude: 115.611519,
      zoom: 14,
      address: "Pejukutan, Kec. Nusa Penida, Kabupaten Klungkung, Bali 80771",
      isFeatured: false,
      position: null,
    },
    {
      countryId: "102",
      islandSlug: "jawa",
      stateId: "1802",
      cityId: "56459",
      categorySlugs: ["water-park"],
      title: "Umbul Kemanten",
      slug: "umbul-kemanten",
      description:
        "Set amid towering trees, this natural spring pool with clear water is a popular spot for swimming.",
      imageUrl:
        "https://static.promediateknologi.id/crop/0x0:0x0/0x0/webp/photo/indizone/2019/07/08/JMspa6/t_5d230789724c2.jpg",
      latitude: -7.5916181,
      longitude: 110.6506105,
      zoom: 17,
      address:
        "Jalan Janti Boto, Boto, Wunut, Kec. Tulung, Kabupaten Klaten, Jawa Tengah 57482",
      position: null,
    },
    {
      countryId: "102",
      islandSlug: "jawa",
      stateId: "1802",
      cityId: "56459",
      categorySlugs: ["water-park"],
      title: "Umbul Ponggok",
      slug: "umbul-ponggok",
      description:
        "Popular with snorkelers & inexperienced divers, this calm natural pool features, sand, rocks & fish.",
      imageUrl: "https://kolomdesa.com/wp-content/uploads/2024/04/109236.jpg",
      latitude: -7.6138103,
      longitude: 110.6358647,
      zoom: 17,
      address:
        "Jl. Delanggu- Polanharjo No.Ds, Jeblogan, Ponggok, Kec. Polanharjo, Kabupaten Klaten, Jawa Tengah 57474",
      position: null,
    },
    {
      countryId: "102",
      islandSlug: "jawa",
      stateId: "1802",
      cityId: "56459",
      categorySlugs: ["water-park"],
      title: "Umbul Cokro",
      slug: "umbul-cokro",
      description:
        "Set amid towering trees, this natural spring pool with clear water is a popular spot for swimming.",
      imageUrl:
        "https://klateninfo.com/wp-content/uploads/2020/09/Foto-Dalam-Air.jpg",
      latitude: -7.6028098,
      longitude: 110.6414273,
      zoom: 17,
      address: "Daleman, Kabupaten Klaten, Jawa Tengah",
      position: null,
    },
    {
      countryId: "102",
      islandSlug: "jawa",
      stateId: "1802",
      cityId: "56505",
      categorySlugs: ["campground", "park"],
      title: "Telomoyo Nature Park",
      slug: "telomoyo-nature-park",
      description: "A beautiful camp ground.",
      imageUrl:
        "https://asset.kompas.com/crops/b4pqG43xd1coE2-9-uuzAsGSEvA=/0x49:1600x1115/750x500/data/photo/2021/08/10/6112334e07071.jpeg",
      latitude: -7.3765102,
      longitude: 110.3951538,
      zoom: 17,
      address:
        "Jalan Ngablak - Grabag No.KM. 1, Pandean Lor, Pandean, Kec. Ngablak, Kabupaten Magelang, Jawa Tengah 56194",
      position: null,
    },
    {
      countryId: "102",
      islandSlug: "kalimantan",
      stateId: "1806",
      cityId: "150102",
      categorySlugs: ["lake"],
      title: "Danau Laet",
      slug: "danau-laet",
      description: "A beautiful lake.",
      imageUrl:
        "https://atourin.obs.ap-southeast-3.myhuaweicloud.com/images/destination/sanggau/danau-laet-profile1640494446.png?x-image-process=image/resize,p_100,limit_1/imageslim",
      latitude: 0.1558683,
      longitude: 109.5625303,
      zoom: 12,
      address:
        "Lalang, Kec. Tayan Hilir, Kabupaten Sanggau, Kalimantan Barat 78564",
      position: null,
    },
    {
      countryId: "102",
      islandSlug: "sulawesi",
      stateId: "1795",
      cityId: "56530",
      categorySlugs: ["nationalpark"],
      title: "Balai Taman Nasional Bantimurung Bulusaraung",
      slug: "bantimurung-bulusaraung",
      description:
        "A vast, mountainous national park known for its karst limestone formations, waterfalls & butterflies.",
      imageUrl: "https://photos.wikimapia.org/p/00/04/30/83/56_big.jpg",
      latitude: -4.7122273,
      longitude: 119.397244,
      zoom: 10,
      address: "Bentenge, Sulawesi Selatan",
      position: null,
    },
    {
      countryId: "102",
      islandSlug: "papua",
      stateId: "1799",
      cityId: "56678",
      categorySlugs: ["nationalpark"],
      title: "Taman Nasional Teluk Cenderawasih",
      slug: "teluk-cenderawasih",
      description:
        "Large marine park popular for snorkeling around the coral reef & swimming with whale sharks.",
      imageUrl:
        "https://ik.imagekit.io/tvlk/blog/2020/03/Taman-Nasional-Teluk-Cendrawasih-NativeIndonesia.jpg",
      latitude: -2.5483309,
      longitude: 132.0395279,
      zoom: 10,
      address: "Sobei Indah, Duairi, Kabupaten Teluk Wondama, Papua Bar. 98362",
      position: null,
    },
    {
      countryId: "102",
      stateId: "1800",
      cityId: "56514",
      categorySlugs: ["beach"],
      title: "Pantai Hunimua Liang",
      slug: "pantai-hunimua-liang",
      description: "Beach with beautiful views",
      imageUrl:
        "https://asset.kompas.com/crops/XE0jgawhv2U8sPgDg47XIcEPgCw=/0x0:1000x667/750x500/data/photo/2022/07/05/62c46106b64c3.jpg",
      latitude: -3.4823135,
      longitude: 128.2581875,
      zoom: 12,
      address:
        "Jl. Propinsi, Liang, Kec. Salahutu, Kabupaten Maluku Tengah, Maluku",
      position: null,
    },
    {
      countryId: "102",
      islandSlug: "kalimantan",
      stateId: "1804",
      cityId: "56190",
      categorySlugs: ["beach"],
      title: "Pantai Melawai",
      slug: "pantai-melawai",
      description:
        "Bustling, sandy urban beach, popular for street-food fare & viewing scenic sunsets.",
      imageUrl:
        "https://cdn.rri.co.id/berita/17/images/1689810734725-pantai_melawai/1689810734725-pantai_melawai.jpg",
      latitude: -1.2713843,
      longitude: 116.7782115,
      zoom: 13,
      address:
        "Jl. Pelabuhan Semayang, Prapatan, Kec. Balikpapan Kota, Kota Balikpapan, Kalimantan Timur 76111",
      position: null,
    },
    {
      countryId: "102",
      islandSlug: "belitung",
      stateId: "1820",
      cityId: "56350",
      categorySlugs: ["beach"],
      title: "Pantai Kiras",
      slug: "pantai-kiras",
      description: "Beach with beautiful views",
      imageUrl:
        "https://static.promediateknologi.id/crop/0x0:0x0/0x0/webp/photo/indizone/2019/07/14/bns6nN/t_5d2a7952a0359.jpg",
      latitude: -3.2248594,
      longitude: 107.5932406,
      zoom: 15,
      address: "Padang Kandis, Belitung Regency, Bangka Belitung Islands",
      position: null,
    },
    {
      countryId: "102",
      islandSlug: "belitung",
      stateId: "1820",
      cityId: "56350",
      categorySlugs: ["beach"],
      title: "Pantai Penyabong",
      slug: "pantai-penyabong",
      description: "Beach with beautiful views",
      imageUrl:
        "https://www.belitungcantiktour.com/wp-content/uploads/2021/06/DJI_0908.jpg",
      latitude: -3.1874969,
      longitude: 107.5774324,
      zoom: 15,
      address:
        "Padang Kandis, Membalong, Belitung Regency, Bangka Belitung Islands 33452",
      position: null,
    },
  ];

  const islands = await prisma.island.findMany({
    select: {
      id: true,
      slug: true,
    },
    where: {
      slug: {
        in: places
          .map((place) => place.islandSlug)
          .filter((slug) => slug !== undefined),
      },
    },
  });

  await Promise.all(
    places.map(async (placeData) => {
      const { categorySlugs, islandSlug, ...place } = placeData;

      const islandId = islands.find((island) => island.slug === islandSlug)?.id;

      await prisma.place.upsert({
        where: { slug: place.slug },
        update: place,
        create: {
          ...place,
          categories: {
            connect: categorySlugs.map((slug) => ({ slug })),
          },
          islandId,
        },
      });
    })
  );
}
